version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=lunar
      - POSTGRES_PASSWORD=lunar
      - POSTGRES_DB=lunar
    ports:
      - "5432:5432"
    volumes:
      - lunar-vol:/var/lib/postgresql/data

  lunar-server:
    build:
      context: ./lunar-server
    ports:
      - "7000:80"
    depends_on:
      - postgres

  lunar-client:
    build:
      context: ./lunar-client
    ports:
      - "6999:80"


volumes:
  lunar-vol:
