version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=lunar
      - POSTGRES_PASSWORD=lunar
      - POSTGRES_DB=lunar
    ports:
      - "5432:5432"
    volumes:
      - lunar-vol:/var/lib/postgresql/data

  lunar-server:
    build:
      context: ./lunar-server
    ports:
      - "7000:80"
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres

  lunar-client:
    build:
      context: ./lunar-client
    ports:
      - "7001:80"

  reverse-proxy: 
    build:
      context: ./
      dockerfile: ./nginx.dockerfile
    ports:
      - "80:80"
    depends_on:
      - lunar-client
      - lunar-server


volumes:
  lunar-vol:
